// HPS_hps_0.v

// This file was auto-generated from altera_hps_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 14.0 200 at 2018.12.24.16:01:28

`timescale 1 ps / 1 ps
module HPS_hps_0 #(
		parameter F2S_Width = 0,
		parameter S2F_Width = 0
	) (
		output wire [66:0] h2f_loan_in,               // h2f_loan_io.in
		input  wire [66:0] h2f_loan_out,              //            .out
		input  wire [66:0] h2f_loan_oe,               //            .oe
		output wire        h2f_rst_n,                 //   h2f_reset.reset_n
		input  wire [31:0] h2f_gp_in,                 //      h2f_gp.gp_in
		output wire [31:0] h2f_gp_out,                //            .gp_out
		output wire [14:0] mem_a,                     //      memory.mem_a
		output wire [2:0]  mem_ba,                    //            .mem_ba
		output wire        mem_ck,                    //            .mem_ck
		output wire        mem_ck_n,                  //            .mem_ck_n
		output wire        mem_cke,                   //            .mem_cke
		output wire        mem_cs_n,                  //            .mem_cs_n
		output wire        mem_ras_n,                 //            .mem_ras_n
		output wire        mem_cas_n,                 //            .mem_cas_n
		output wire        mem_we_n,                  //            .mem_we_n
		output wire        mem_reset_n,               //            .mem_reset_n
		inout  wire [31:0] mem_dq,                    //            .mem_dq
		inout  wire [3:0]  mem_dqs,                   //            .mem_dqs
		inout  wire [3:0]  mem_dqs_n,                 //            .mem_dqs_n
		output wire        mem_odt,                   //            .mem_odt
		output wire [3:0]  mem_dm,                    //            .mem_dm
		input  wire        oct_rzqin,                 //            .oct_rzqin
		inout  wire        hps_io_gpio_inst_LOANIO01, //      hps_io.hps_io_gpio_inst_LOANIO01
		inout  wire        hps_io_gpio_inst_LOANIO02, //            .hps_io_gpio_inst_LOANIO02
		inout  wire        hps_io_gpio_inst_LOANIO03, //            .hps_io_gpio_inst_LOANIO03
		inout  wire        hps_io_gpio_inst_LOANIO04, //            .hps_io_gpio_inst_LOANIO04
		inout  wire        hps_io_gpio_inst_LOANIO05, //            .hps_io_gpio_inst_LOANIO05
		inout  wire        hps_io_gpio_inst_LOANIO06, //            .hps_io_gpio_inst_LOANIO06
		inout  wire        hps_io_gpio_inst_LOANIO07, //            .hps_io_gpio_inst_LOANIO07
		inout  wire        hps_io_gpio_inst_LOANIO08, //            .hps_io_gpio_inst_LOANIO08
		inout  wire        hps_io_gpio_inst_LOANIO10, //            .hps_io_gpio_inst_LOANIO10
		inout  wire        hps_io_gpio_inst_LOANIO11, //            .hps_io_gpio_inst_LOANIO11
		inout  wire        hps_io_gpio_inst_LOANIO12, //            .hps_io_gpio_inst_LOANIO12
		inout  wire        hps_io_gpio_inst_LOANIO13, //            .hps_io_gpio_inst_LOANIO13
		inout  wire        hps_io_gpio_inst_LOANIO42, //            .hps_io_gpio_inst_LOANIO42
		inout  wire        hps_io_gpio_inst_LOANIO49, //            .hps_io_gpio_inst_LOANIO49
		inout  wire        hps_io_gpio_inst_LOANIO50  //            .hps_io_gpio_inst_LOANIO50
	);

	wire  [28:0] hps_io_gpio_loanio_loanio0_i;           // hps_io:gpio_loanio_loanio0_i -> fpga_interfaces:loanio_gpio_loanio0_i
	wire  [28:0] fpga_interfaces_loanio_gpio_loanio1_o;  // fpga_interfaces:loanio_gpio_loanio1_o -> hps_io:gpio_loanio_loanio1_o
	wire   [8:0] fpga_interfaces_loanio_gpio_loanio2_o;  // fpga_interfaces:loanio_gpio_loanio2_o -> hps_io:gpio_loanio_loanio2_o
	wire   [8:0] fpga_interfaces_loanio_gpio_loanio2_oe; // fpga_interfaces:loanio_gpio_loanio2_oe -> hps_io:gpio_loanio_loanio2_oe
	wire   [8:0] hps_io_gpio_loanio_loanio2_i;           // hps_io:gpio_loanio_loanio2_i -> fpga_interfaces:loanio_gpio_loanio2_i
	wire  [28:0] hps_io_gpio_loanio_loanio1_i;           // hps_io:gpio_loanio_loanio1_i -> fpga_interfaces:loanio_gpio_loanio1_i
	wire  [28:0] fpga_interfaces_loanio_gpio_loanio1_oe; // fpga_interfaces:loanio_gpio_loanio1_oe -> hps_io:gpio_loanio_loanio1_oe
	wire  [28:0] fpga_interfaces_loanio_gpio_loanio0_o;  // fpga_interfaces:loanio_gpio_loanio0_o -> hps_io:gpio_loanio_loanio0_o
	wire  [28:0] fpga_interfaces_loanio_gpio_loanio0_oe; // fpga_interfaces:loanio_gpio_loanio0_oe -> hps_io:gpio_loanio_loanio0_oe

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (F2S_Width != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					f2s_width_check ( .error(1'b1) );
		end
		if (S2F_Width != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					s2f_width_check ( .error(1'b1) );
		end
	endgenerate

	HPS_hps_0_fpga_interfaces fpga_interfaces (
		.h2f_loan_in            (h2f_loan_in),                            // h2f_loan_io.in
		.h2f_loan_out           (h2f_loan_out),                           //            .out
		.h2f_loan_oe            (h2f_loan_oe),                            //            .oe
		.loanio_gpio_loanio0_i  (hps_io_gpio_loanio_loanio0_i),           // loanio_gpio.loanio0_i
		.loanio_gpio_loanio0_oe (fpga_interfaces_loanio_gpio_loanio0_oe), //            .loanio0_oe
		.loanio_gpio_loanio0_o  (fpga_interfaces_loanio_gpio_loanio0_o),  //            .loanio0_o
		.loanio_gpio_loanio1_i  (hps_io_gpio_loanio_loanio1_i),           //            .loanio1_i
		.loanio_gpio_loanio1_oe (fpga_interfaces_loanio_gpio_loanio1_oe), //            .loanio1_oe
		.loanio_gpio_loanio1_o  (fpga_interfaces_loanio_gpio_loanio1_o),  //            .loanio1_o
		.loanio_gpio_loanio2_i  (hps_io_gpio_loanio_loanio2_i),           //            .loanio2_i
		.loanio_gpio_loanio2_oe (fpga_interfaces_loanio_gpio_loanio2_oe), //            .loanio2_oe
		.loanio_gpio_loanio2_o  (fpga_interfaces_loanio_gpio_loanio2_o),  //            .loanio2_o
		.h2f_rst_n              (h2f_rst_n),                              //   h2f_reset.reset_n
		.h2f_gp_in              (h2f_gp_in),                              //      h2f_gp.gp_in
		.h2f_gp_out             (h2f_gp_out)                              //            .gp_out
	);

	HPS_hps_0_hps_io hps_io (
		.gpio_loanio_loanio0_i     (hps_io_gpio_loanio_loanio0_i),           // gpio_loanio.loanio0_i
		.gpio_loanio_loanio0_oe    (fpga_interfaces_loanio_gpio_loanio0_oe), //            .loanio0_oe
		.gpio_loanio_loanio0_o     (fpga_interfaces_loanio_gpio_loanio0_o),  //            .loanio0_o
		.gpio_loanio_loanio1_i     (hps_io_gpio_loanio_loanio1_i),           //            .loanio1_i
		.gpio_loanio_loanio1_oe    (fpga_interfaces_loanio_gpio_loanio1_oe), //            .loanio1_oe
		.gpio_loanio_loanio1_o     (fpga_interfaces_loanio_gpio_loanio1_o),  //            .loanio1_o
		.gpio_loanio_loanio2_i     (hps_io_gpio_loanio_loanio2_i),           //            .loanio2_i
		.gpio_loanio_loanio2_oe    (fpga_interfaces_loanio_gpio_loanio2_oe), //            .loanio2_oe
		.gpio_loanio_loanio2_o     (fpga_interfaces_loanio_gpio_loanio2_o),  //            .loanio2_o
		.mem_a                     (mem_a),                                  //      memory.mem_a
		.mem_ba                    (mem_ba),                                 //            .mem_ba
		.mem_ck                    (mem_ck),                                 //            .mem_ck
		.mem_ck_n                  (mem_ck_n),                               //            .mem_ck_n
		.mem_cke                   (mem_cke),                                //            .mem_cke
		.mem_cs_n                  (mem_cs_n),                               //            .mem_cs_n
		.mem_ras_n                 (mem_ras_n),                              //            .mem_ras_n
		.mem_cas_n                 (mem_cas_n),                              //            .mem_cas_n
		.mem_we_n                  (mem_we_n),                               //            .mem_we_n
		.mem_reset_n               (mem_reset_n),                            //            .mem_reset_n
		.mem_dq                    (mem_dq),                                 //            .mem_dq
		.mem_dqs                   (mem_dqs),                                //            .mem_dqs
		.mem_dqs_n                 (mem_dqs_n),                              //            .mem_dqs_n
		.mem_odt                   (mem_odt),                                //            .mem_odt
		.mem_dm                    (mem_dm),                                 //            .mem_dm
		.oct_rzqin                 (oct_rzqin),                              //            .oct_rzqin
		.hps_io_gpio_inst_LOANIO01 (hps_io_gpio_inst_LOANIO01),              //      hps_io.hps_io_gpio_inst_LOANIO01
		.hps_io_gpio_inst_LOANIO02 (hps_io_gpio_inst_LOANIO02),              //            .hps_io_gpio_inst_LOANIO02
		.hps_io_gpio_inst_LOANIO03 (hps_io_gpio_inst_LOANIO03),              //            .hps_io_gpio_inst_LOANIO03
		.hps_io_gpio_inst_LOANIO04 (hps_io_gpio_inst_LOANIO04),              //            .hps_io_gpio_inst_LOANIO04
		.hps_io_gpio_inst_LOANIO05 (hps_io_gpio_inst_LOANIO05),              //            .hps_io_gpio_inst_LOANIO05
		.hps_io_gpio_inst_LOANIO06 (hps_io_gpio_inst_LOANIO06),              //            .hps_io_gpio_inst_LOANIO06
		.hps_io_gpio_inst_LOANIO07 (hps_io_gpio_inst_LOANIO07),              //            .hps_io_gpio_inst_LOANIO07
		.hps_io_gpio_inst_LOANIO08 (hps_io_gpio_inst_LOANIO08),              //            .hps_io_gpio_inst_LOANIO08
		.hps_io_gpio_inst_LOANIO10 (hps_io_gpio_inst_LOANIO10),              //            .hps_io_gpio_inst_LOANIO10
		.hps_io_gpio_inst_LOANIO11 (hps_io_gpio_inst_LOANIO11),              //            .hps_io_gpio_inst_LOANIO11
		.hps_io_gpio_inst_LOANIO12 (hps_io_gpio_inst_LOANIO12),              //            .hps_io_gpio_inst_LOANIO12
		.hps_io_gpio_inst_LOANIO13 (hps_io_gpio_inst_LOANIO13),              //            .hps_io_gpio_inst_LOANIO13
		.hps_io_gpio_inst_LOANIO42 (hps_io_gpio_inst_LOANIO42),              //            .hps_io_gpio_inst_LOANIO42
		.hps_io_gpio_inst_LOANIO49 (hps_io_gpio_inst_LOANIO49),              //            .hps_io_gpio_inst_LOANIO49
		.hps_io_gpio_inst_LOANIO50 (hps_io_gpio_inst_LOANIO50)               //            .hps_io_gpio_inst_LOANIO50
	);

endmodule
