set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO01] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO01]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO02] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO02]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO03] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO03]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO04] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO04]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO05] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO05]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO06] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO06]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO07] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO07]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO08] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO08]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO10] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO10]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO11] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO11]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO12] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO12]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO13] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO13]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO42] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO42]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO49] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO49]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO50] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO50]