	HPS u0 (
		.memory_mem_a                     (<connected-to-memory_mem_a>),                     // memory.mem_a
		.memory_mem_ba                    (<connected-to-memory_mem_ba>),                    //       .mem_ba
		.memory_mem_ck                    (<connected-to-memory_mem_ck>),                    //       .mem_ck
		.memory_mem_ck_n                  (<connected-to-memory_mem_ck_n>),                  //       .mem_ck_n
		.memory_mem_cke                   (<connected-to-memory_mem_cke>),                   //       .mem_cke
		.memory_mem_cs_n                  (<connected-to-memory_mem_cs_n>),                  //       .mem_cs_n
		.memory_mem_ras_n                 (<connected-to-memory_mem_ras_n>),                 //       .mem_ras_n
		.memory_mem_cas_n                 (<connected-to-memory_mem_cas_n>),                 //       .mem_cas_n
		.memory_mem_we_n                  (<connected-to-memory_mem_we_n>),                  //       .mem_we_n
		.memory_mem_reset_n               (<connected-to-memory_mem_reset_n>),               //       .mem_reset_n
		.memory_mem_dq                    (<connected-to-memory_mem_dq>),                    //       .mem_dq
		.memory_mem_dqs                   (<connected-to-memory_mem_dqs>),                   //       .mem_dqs
		.memory_mem_dqs_n                 (<connected-to-memory_mem_dqs_n>),                 //       .mem_dqs_n
		.memory_mem_odt                   (<connected-to-memory_mem_odt>),                   //       .mem_odt
		.memory_mem_dm                    (<connected-to-memory_mem_dm>),                    //       .mem_dm
		.memory_oct_rzqin                 (<connected-to-memory_oct_rzqin>),                 //       .oct_rzqin
		.hps_io_hps_io_gpio_inst_LOANIO01 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO01>), // hps_io.hps_io_gpio_inst_LOANIO01
		.hps_io_hps_io_gpio_inst_LOANIO02 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO02>), //       .hps_io_gpio_inst_LOANIO02
		.hps_io_hps_io_gpio_inst_LOANIO03 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO03>), //       .hps_io_gpio_inst_LOANIO03
		.hps_io_hps_io_gpio_inst_LOANIO04 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO04>), //       .hps_io_gpio_inst_LOANIO04
		.hps_io_hps_io_gpio_inst_LOANIO05 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO05>), //       .hps_io_gpio_inst_LOANIO05
		.hps_io_hps_io_gpio_inst_LOANIO06 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO06>), //       .hps_io_gpio_inst_LOANIO06
		.hps_io_hps_io_gpio_inst_LOANIO07 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO07>), //       .hps_io_gpio_inst_LOANIO07
		.hps_io_hps_io_gpio_inst_LOANIO08 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO08>), //       .hps_io_gpio_inst_LOANIO08
		.hps_io_hps_io_gpio_inst_LOANIO10 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO10>), //       .hps_io_gpio_inst_LOANIO10
		.hps_io_hps_io_gpio_inst_LOANIO11 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO11>), //       .hps_io_gpio_inst_LOANIO11
		.hps_io_hps_io_gpio_inst_LOANIO12 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO12>), //       .hps_io_gpio_inst_LOANIO12
		.hps_io_hps_io_gpio_inst_LOANIO13 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO13>), //       .hps_io_gpio_inst_LOANIO13
		.hps_io_hps_io_gpio_inst_LOANIO42 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO42>), //       .hps_io_gpio_inst_LOANIO42
		.hps_io_hps_io_gpio_inst_LOANIO49 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO49>), //       .hps_io_gpio_inst_LOANIO49
		.hps_io_hps_io_gpio_inst_LOANIO50 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO50>), //       .hps_io_gpio_inst_LOANIO50
		.loanio_in                        (<connected-to-loanio_in>),                        // loanio.in
		.loanio_out                       (<connected-to-loanio_out>),                       //       .out
		.loanio_oe                        (<connected-to-loanio_oe>),                        //       .oe
		.hps_gp_gp_in                     (<connected-to-hps_gp_gp_in>),                     // hps_gp.gp_in
		.hps_gp_gp_out                    (<connected-to-hps_gp_gp_out>)                     //       .gp_out
	);

